server:
  port: 8880

spring:
  application:
    name: xjt-travel

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:13306/xjt_springboot_travel?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 3000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xjt.travel.domain

# 地域节点
aliyun:
  oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    urlPrefix: xiong-test-srt.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5t92emGmUukAv8DuDmL4
    accessKeySecret: VcCRXc012UcSvANZPvqFam9wrekhME
    bucketName: xiong-test-srt
    fileHost: files

